// Code generated by data/gen; DO NOT EDIT.

package registry

var foodItemIDs = map[int32]bool{
	800:  true,
	849:  true,
	855:  true,
	881:  true,
	882:  true,
	884:  true,
	885:  true,
	935:  true,
	936:  true,
	937:  true,
	938:  true,
	939:  true,
	940:  true,
	980:  true,
	984:  true,
	985:  true,
	988:  true,
	989:  true,
	990:  true,
	991:  true,
	992:  true,
	1000: true,
	1097: true,
	1098: true,
	1099: true,
	1100: true,
	1102: true,
	1111: true,
	1118: true,
	1119: true,
	1120: true,
	1131: true,
	1132: true,
	1150: true,
	1154: true,
	1156: true,
	1193: true,
	1216: true,
	1217: true,
	1224: true,
	1331: true,
}

func IsFoodItem(id int32) bool {
	return foodItemIDs[id]
}
