//go:build ignore

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"text/template"
)

type ViewDef struct {
	Name       string
	Mask       string
	Components []string
}

func main() {
	views := []ViewDef{
		{
			Name: "Movement",
			Mask: "model.ConnectedBotMask",
			Components: []string{
				"Position", "Velocity",
			},
		},
		{
			Name: "Health",
			Mask: "model.ConnectedBotMask",
			Components: []string {
				"Health",
			},
		},
	}

	tmpl := `
	// Code generated by go generate, source in gen.go; DO NOT EDIT.
	package core

	import (
		"minecraft_orchestrator/internal/engine/model"
	)

	{{range .}}
type {{.Name}}View struct {
		Entities []Entity
		{{range .Components}}
		{{.}}s []model.{{.}}
		{{end}}
}

func (w *World) {{.Name}}Views() []{{.Name}}View {
		tables := w.matching({{.Mask}})
		result := make([]{{.Name}}View, 0, len(tables))

		for _, table := range tables {
			result = append(result, {{.Name}}View{
				Entities: table.entities,
				{{range .Components}}
				{{.}}s: table.columns[uint8(model.C{{.}})].(*Column[model.{{.}}]).Data,
				{{end}}
			})
		}
		return result
}
{{end}}
	`

	t := template.Must(template.New("views").Parse(tmpl))

	var buf bytes.Buffer
	if err := t.Execute(&buf, views); err != nil {
		log.Fatal(err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("views_generated.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
}
