// Code generated by go generate, source in gen.go; DO NOT EDIT.
package core

import (
	"minecraft_orchestrator/internal/engine/model"
)

type MirroredBotView struct {
	Entities []Entity

	Bots []model.Bot

	Sessions []model.Session

	Positions []model.Position

	Rotations []model.Rotation

	Velocitys []model.Velocity

	Healths []model.Health

	Hungers []model.Hunger

	GameModes []model.GameMode

	Inventorys []model.Inventory

	Effectss []model.Effects

	UtilityAIs []model.UtilityAI

	ControllerSyncs []model.ControllerSync
}

func (w *World) MirroredBotViews() []MirroredBotView {
	tables := w.matching(model.MirroredBotMask)
	result := make([]MirroredBotView, 0, len(tables))

	for _, table := range tables {
		result = append(result, MirroredBotView{
			Entities: table.entities,

			Bots: table.columns[uint8(model.CBot)].(*Column[model.Bot]).Data,

			Sessions: table.columns[uint8(model.CSession)].(*Column[model.Session]).Data,

			Positions: table.columns[uint8(model.CPosition)].(*Column[model.Position]).Data,

			Rotations: table.columns[uint8(model.CRotation)].(*Column[model.Rotation]).Data,

			Velocitys: table.columns[uint8(model.CVelocity)].(*Column[model.Velocity]).Data,

			Healths: table.columns[uint8(model.CHealth)].(*Column[model.Health]).Data,

			Hungers: table.columns[uint8(model.CHunger)].(*Column[model.Hunger]).Data,

			GameModes: table.columns[uint8(model.CGameMode)].(*Column[model.GameMode]).Data,

			Inventorys: table.columns[uint8(model.CInventory)].(*Column[model.Inventory]).Data,

			Effectss: table.columns[uint8(model.CEffects)].(*Column[model.Effects]).Data,

			UtilityAIs: table.columns[uint8(model.CUtilityAI)].(*Column[model.UtilityAI]).Data,

			ControllerSyncs: table.columns[uint8(model.CControllerSync)].(*Column[model.ControllerSync]).Data,
		})
	}
	return result
}
